# Generated by Django 4.2 on 2023-04-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='Services',
        ),
    ]
