# Generated by Django 4.2 on 2023-04-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='User_profile',
        ),
    ]
